### ISSUE TITLE
Error 1556 when creating cRIO item in Configuration Editor

### ISSUE THREAD

**Issue by fmussi** [LabVIEW-DCAF/DCAF-Core#2] opened 2016-11-30 11:00 UTC
Using LV 2016 and DCAF Core 1.0.0.8 (and dependent) package.

-) Create project from a Basic Execution Template
-) Open DCAF configurator editor
-) Add new cRIO item
-) when selecting target type (e.g. Linux ARM x64), you get the error below 

![image](https://cloud.githubusercontent.com/assets/8535457/20749683/9a82ee66-b6f3-11e6-83cf-9818fe7592e1.png)

If I try to ignore it, I can work again on the editor, but if I try to add a target item again, I still get error 1556
If I close the DCAF editor and open it again, error still shows up

**Comment by fmussi** [comment] 2016-11-30 11:01
One more things: using an existing configuration file (e.g. the temperature controller one) works without issues.

**Comment by fmussi** [comment] 2016-11-30 11:13
Another update: it seems the error shows up if you create the cRIO item under Systems (I haven't tried with other items types like cDAQ, etc) and do not add an engine under it. If you add a standard engine for example,

![Uploading image.png…]()

 then you can go back on cRIO item and modify any field without errors.

**Comment by Beazurt** [comment] 2016-12-01 14:00
This is a duplicate of this issue which has already been fixed.  

https://github.com/LabVIEW-DCAF/TagEditorCore/issues/238

**Closed as completed by Beazurt** 2016-12-01 14:00 UTC
Labels: duplicate
